name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
     
      - name: deploy
        env:
          CI: true
        run: |
          npx ncc build index.ts
          Compress-Archive -Path .\dist\* -DestinationPath .\deploy.zip
          # aws cli - deploy code